// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/Tasklist/CreateCategory": {
            "post": {
                "parameters": [
                    {
                        "description": "Inserting Data",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateCategoryParam"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/Tasklist/DownloadingToMongoDB": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Upload a file",
                "responses": {
                    "200": {
                        "description": "Successfully uploaded",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/Tasklist/FetchData_Assign_To": {
            "get": {
                "responses": {}
            }
        },
        "/Tasklist/GetCategory": {
            "get": {
                "description": "Get list of categories based on parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Get category list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category parameter",
                        "name": "param",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CategoryList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/Tasklist/GetDepartemen": {
            "get": {
                "description": "Get all departments from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Get list of departments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DeptList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/Tasklist/GetHeaderListData": {
            "get": {
                "responses": {}
            }
        },
        "/Tasklist/GetIncomingTask": {
            "get": {
                "responses": {}
            }
        },
        "/Tasklist/GetListData": {
            "get": {
                "description": "Get various types of list data based on parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Get list data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Parameter type (GetDataHeaderTaskList/GetDataDetailTaskList/SetDataSummaryTaskList/GetDataAssignTo/GetDataAssignToALL/ValidateUserLevel)",
                        "name": "param",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "task_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/Tasklist/GetListUserAssignHistory": {
            "get": {
                "responses": {}
            }
        },
        "/Tasklist/GetListtComments": {
            "get": {
                "description": "Get comments for a specific task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Get list of comments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "task_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetCommentList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/Tasklist/GetNotifTaskList": {
            "get": {
                "responses": {}
            }
        },
        "/Tasklist/GetTaskCategory": {
            "get": {
                "description": "Get all task categories from the task_category table",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Get task category list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TaskCategory"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/Tasklist/GetTaskID": {
            "get": {
                "description": "Get task ID information using comment ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Get task ID by comment ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment ID",
                        "name": "comment_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ValueGetTaskID"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/Tasklist/GetUserNotifTaskList": {
            "get": {
                "responses": {}
            }
        },
        "/Tasklist/GetUserid": {
            "get": {
                "description": "Get user information by PIN",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Get user information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Parameter type (GetUserid/GetUserName)",
                        "name": "param",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User PIN",
                        "name": "pin",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ValueGettingUserid"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/Tasklist/InsertSchedulerMasterTask": {
            "post": {
                "parameters": [
                    {
                        "description": "Inserting Data",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.InsertSchedulerMasterTaskList"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/Tasklist/InsertUpdategroupAssignTO": {
            "post": {
                "parameters": [
                    {
                        "description": "Inserting Data",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.InsertUpdategroupAssignTOModels"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/Tasklist/InsertingComment": {
            "post": {
                "parameters": [
                    {
                        "description": "Inserting Comments",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.InsertComments"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/Tasklist/InsertingDocumentUpload": {
            "post": {
                "parameters": [
                    {
                        "description": "Inserting Document Upload",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.InsertDocument"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/Tasklist/InsertingSubtask": {
            "post": {
                "summary": "Inserting Subtask",
                "parameters": [
                    {
                        "description": "Inserting Task Manual",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.InsertingTaskManual"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully uploaded",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/Tasklist/InsertingTaskManual": {
            "post": {
                "description": "Upload a file to the specified bucket using the file path and file name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Inserting Task Manual",
                "parameters": [
                    {
                        "description": "Inserting Task Manual",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.InsertingTaskManual"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully uploaded",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/Tasklist/SendingNotifDone": {
            "post": {
                "summary": "SendingNotifDone",
                "parameters": [
                    {
                        "description": "Inserting Task Manual",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.WaitingToCloseEmail"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully uploaded",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/Tasklist/UpdateStatusClickednotif": {
            "post": {
                "parameters": [
                    {
                        "description": "File Upload Info",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ParamClickedNotif"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/Tasklist/UpdatingProgressTask": {
            "post": {
                "description": "Upload a file to the specified bucket using the file path and file name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Inserting Task Manual",
                "parameters": [
                    {
                        "description": "Updating Progress Task Value",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ValueUpdateingTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully uploaded",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/Tasklist/UploadFile": {
            "post": {
                "description": "Upload a file to the specified bucket using the file path and file name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Upload a file",
                "parameters": [
                    {
                        "description": "File Upload Info",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.FileUpload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully uploaded",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/Tasklist/UploadingToMongoDB": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Upload a file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully uploaded",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/Tasklist/UploadingToMongoDB_V1": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Upload a file",
                "parameters": [
                    {
                        "description": "File Upload Info",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.FileUpload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully uploaded",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/Tasklist/ValidateDocType": {
            "get": {
                "description": "Validate document type for a given task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Get document type validation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "param",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CategoryList": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.CreateCategoryParam": {
            "type": "object",
            "required": [
                "category",
                "name"
            ],
            "properties": {
                "category": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.DeptList": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.FileUpload": {
            "type": "object",
            "required": [
                "fileName",
                "filePath"
            ],
            "properties": {
                "fileName": {
                    "type": "string"
                },
                "filePath": {
                    "type": "string"
                }
            }
        },
        "models.GetCommentList": {
            "type": "object",
            "properties": {
                "Comment_Date": {
                    "type": "string"
                },
                "Comment_ID": {
                    "type": "string"
                },
                "Comments": {
                    "type": "string"
                },
                "Content_Name": {
                    "type": "string"
                },
                "Emp_ID": {
                    "type": "string"
                },
                "Emp_NAME": {
                    "type": "string"
                },
                "File_ID": {
                    "type": "string"
                }
            }
        },
        "models.InsertComments": {
            "type": "object",
            "required": [
                "Comments",
                "Emp_ID",
                "Task_ID"
            ],
            "properties": {
                "Comments": {
                    "type": "string"
                },
                "Content_Name": {
                    "type": "string"
                },
                "Emp_ID": {
                    "type": "string"
                },
                "File_Path": {
                    "type": "string"
                },
                "Tagging_User": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "Task_ID": {
                    "type": "string"
                }
            }
        },
        "models.InsertDocument": {
            "type": "object",
            "required": [
                "CreatedDate",
                "DocumentType",
                "Status",
                "TaskID"
            ],
            "properties": {
                "CreatedDate": {
                    "type": "string"
                },
                "DocumentName": {
                    "type": "string"
                },
                "DocumentType": {
                    "type": "string"
                },
                "FilePath": {
                    "type": "string"
                },
                "Status": {
                    "type": "string"
                },
                "TaskID": {
                    "type": "string"
                }
            }
        },
        "models.InsertSchedulerMasterTaskList": {
            "type": "object",
            "properties": {
                "assign_to": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "dept": {
                    "type": "string"
                },
                "estimasted_time_done": {
                    "type": "string"
                },
                "generate_every": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                },
                "remainder_date": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "task_category": {
                    "type": "string"
                },
                "task_name": {
                    "type": "string"
                },
                "task_type": {
                    "type": "string"
                },
                "topic_code": {
                    "type": "string"
                }
            }
        },
        "models.InsertUpdategroupAssignTOModels": {
            "type": "object",
            "properties": {
                "p_assigner": {
                    "type": "string"
                },
                "p_group_assign": {
                    "type": "string"
                },
                "p_param": {
                    "type": "string"
                },
                "p_task_id": {
                    "type": "string"
                },
                "p_user_assign_to": {
                    "type": "string"
                }
            }
        },
        "models.InsertingTaskManual": {
            "type": "object",
            "properties": {
                "addwho": {
                    "type": "string"
                },
                "assign_to": {
                    "type": "string"
                },
                "departemen": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                },
                "remainder_date": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "task_id_parent_of": {
                    "type": "string"
                },
                "task_name": {
                    "type": "string"
                },
                "task_type": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                }
            }
        },
        "models.ParamClickedNotif": {
            "type": "object",
            "properties": {
                "taskid": {
                    "type": "string"
                }
            }
        },
        "models.TaskCategory": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "models.ValueGetTaskID": {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "string"
                }
            }
        },
        "models.ValueGettingUserid": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "number_officer": {
                    "type": "string"
                }
            }
        },
        "models.ValueUpdateingTask": {
            "type": "object",
            "properties": {
                "progresvalue": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                }
            }
        },
        "models.WaitingToCloseEmail": {
            "type": "object",
            "properties": {
                "addwho": {
                    "type": "string"
                },
                "assign_to": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8086",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Tasklist API",
	Description:      "A Tasklist management service API in Go using Gin framework.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
